### ISSUE TITLE
ASCII or other program-friendly output mode

### ISSUE THREAD

**Issue by itowlson** [corneliusweig/rakkess#5]
At the moment, the only output I can see from `rakess` uses colour escape sequences.  This doesn't display well in PowerShell, and isn't very convenient for consuming programmatically (e.g. from a GUI tool).  Would you be open to a PR for an "ASCII display" flag or similar?

**Comment by corneliusweig** [comment]
You are raising two separate points.
1) Color output. This is disabled for non-terminals, e.g. `rakkess | cat` or `rakkess > result.txt` do not produce colors. Also, PowerShell should (I can't check) not output colors, because this is determined at pkg/rakkess/util/printer.go:79 with
   ```
   func IsTerminal(fd int) bool {  
	_, err := unix.IoctlGetTermios(fd, ioctlReadTermios)
	return err == nil
   }
   ```
   PowerShell being not unix, _should_ return false here.
   So I _think_ color output is fine and does not need work (you can prove me wrong if you have a PowerShell :) )

2) Ascii formatting. This is a good point. What do you think about a flag `--ascii` or `--ascii-mode` so that granted/denied is printed as `yes/no` or even `granted/denied`? pkg/rakkess/util/printer.go is where you would want to start.

**Comment by itowlson** [comment]
Good point - I am indeed mixing two things.

As you say, PowerShell does not support colour, but what I found was that rakkess still printed the escape codes - but they were rendered as codes and square brackets.  I can retry tomorrow and post a screenshot if that would be useful.  I think on Draft we gave up trying to be clever about this and just turned colours off on Windows!

Anyway you are right that these are two separate issues.  I'd be interested in tackling ASCII output if you are okay with that.  I suggest that ASCII formatting should automatically suppress colours, and I'd tentatively go with `yes/no`.  Other ideas are `granted/denied` as you suggest, or `allowed/denied`.  Let me know if you have a preference, otherwise I'll try to get you a PR and we can iterate on it there!  And thanks for the pointer on the `printer.go` starting point.

**Comment by corneliusweig** [comment]
@itowlson Oh please do go ahead with the ascii formatting. I think `yes/no` is just fine. For now I like your idea to disable coloring in ascii mode. However, ideally we should turn it on again, if we can reliably detect a PowerShell terminal.

I've also opened another issue to track the coloring on PowerShell #6. Since I cannot investigate this, could you kindly look into this as well?

**Comment by lgmorand** [comment]
![image](https://user-images.githubusercontent.com/6757079/94377954-a6df4580-0125-11eb-9b93-b05511abd162.png)
any idea what could cause encoding issues under WSL (Windows Linux Subsystem). that the first time, I have encoding issues with bash

**Comment by corneliusweig** [comment]
@lgmorand unfortunately no. IIUC, you are saying that other UTF encoded text prints correctly, right? If anyone knows, I bet @itowlson does.
Maybe open a separate issue so that other folks can find the bug.

**Comment by lgmorand** [comment]
@corneliusweig exactly. it's def looks like an encoding issue but it seems a common, with not clear solution: https://github.com/microsoft/terminal/issues/190

I don't use Windows Terminal but I don't believe in coincidences :)
